return {
  {
    "nvim-lualine/lualine.nvim",
    event = "VeryLazy",
    opts = function()
      -- lualine/themes/dms.lua is generated by DMS and needs base46; fall back
      -- to base16 when it isn't there.
      local theme = pcall(require, "lualine.themes.dms") and "dms" or "base16"
      return {
        options = { theme = theme },
      }
    end,
  },
}
