return {
  {
    "nvim-lualine/lualine.nvim",
    event = "VeryLazy",
    -- Merge into LazyVim's lualine opts (sections, extensions, globalstatus...)
    -- rather than returning a fresh table, which would replace them.
    opts = function(_, opts)
      -- lualine/themes/dms.lua is generated by DMS and needs base46; fall back
      -- to base16 when it isn't there.
      opts.options = opts.options or {}
      opts.options.theme = pcall(require, "lualine.themes.dms") and "dms" or "base16"
    end,
  },
}
